

services:
  backend:
    build: ./BackEnd
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/BSC-Messenger
    depends_on:
      - db
  
  frontend:
    build: ./FrontEnd
    ports:
      - "5173:5173" 
    volumes:
      - ./ssl:/app/ssl:ro  # Monte les certificats SSL en lecture seule
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=BSC-Messenger
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: